#pragma config(Motor,  port1,           RightFrontMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RightLiftMotor1, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightLiftMotor2, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Intake2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftLiftMotor2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftLiftMotor1, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftFrontMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
  	//Right side of the robot is controlled by the right joystick, Y-axis
    motor[RightFrontMotor] = vexRT[Ch2];  ///////////////////////////////////
    motor[RightBackMotor]  = vexRT[Ch2];  //
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[LeftFrontMotor] = vexRT[Ch3];  //
    motor[LeftBackMotor]  = vexRT[Ch3];  // /////////////////////////////////DRIVES THE ROBOT CONTROLLING THE JOYSTICK

 if(vexRT[Btn6U] == 1)
    {
    	motor[LeftLiftMotor1] = 75;///// // /////////////////////////////////////////////////////////////
    	motor[LeftLiftMotor2] = 75;//
    	motor[RightLiftMotor1] = 75;//
    	motor[RightLiftMotor2] = 75;//
    }
    else if(vexRT[Btn6D] == 1)////////////////////////////THIS CONTROLLS THE LIFT//////////////////////
    {
    	motor[LeftLiftMotor1] = -75;//
    	motor[LeftLiftMotor2] = -75;//
    	motor[RightLiftMotor1] = -75;//
    	motor[RightLiftMotor2] = -75;//
    }
   	else
    {
    	motor[LeftLiftMotor1] = 0;//
    	motor[LeftLiftMotor2] = 0;//
    	motor[RightLiftMotor1] = 0;//
    	motor[RightLiftMotor2] = 0;/////////////////////////////////////////////////////////////////////
 	 	}

 	 if(vexRT[Btn5U] == 1)//////////////////////////////////////
 	 	{
 	 		motor[Intake1] = 127;//
 	 		motor[Intake2] = 127;


 		}
 	 else if (vexRT[Btn5D] == 1)///////////////////////THIS CONTROLLS THE INTAKE
 		{
 			motor[Intake1] = -127;//
 			motor[Intake2] = -127;

 		}
 		else
 		{
 			motor[Intake1] = 0;//
 			motor[Intake2] = 0;
 			////////////////////////////////
 		}



	}
}
