#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port1,           L1,            tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           L2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           L3,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L4,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           L5,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           L6,            tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void launcher (int speed)
{
	motor[L1]=speed;
	motor[L2]=speed;
	motor[L3]=speed;
	motor[L4]=speed;
	motor[L5]=speed;
	motor[L6]=speed;
}

task main()
{
	while(true)
{
launcher(vexRT(Ch2));

}


}
