#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    X_accel,        sensorAccelerometer)
#pragma config(Sensor, in2,    Y_accel,        sensorAccelerometer)
#pragma config(Sensor, in3,    Z_accel,        sensorAccelerometer)
#pragma config(Sensor, in4,    UpLightSensor,  sensorLineFollower)
#pragma config(Sensor, in5,    BtmLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LauncherIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          UpIntake,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void startup ()
{
		motor[LBtmL]= -20;
		motor[LMidL]= -20;
		motor[LUpL] = -20;
		motor[RBtmL]= -20;
		motor[RUpL] = -20;
		motor[RUpL] = -20;
}

bool buttonPressed2 = false;
bool buttonPressed = false;
int additionalSpeed = 0;

task main()
{
	while (true)
	{
		motor[LBtmL]= (vexRT(Ch2) + additionalSpeed);
		motor[LMidL]= (vexRT(Ch2) + additionalSpeed);
		motor[LUpL] = (vexRT(Ch2) + additionalSpeed);
		motor[RBtmL]= (vexRT(Ch2) + additionalSpeed);
		motor[RUpL] = (vexRT(Ch2) + additionalSpeed);
		motor[RUpL] = (vexRT(Ch2) + additionalSpeed);
	}
	if(vexRT[Btn6U] ==1)
	{
		buttonPressed = true;
	}
	if(buttonPressed== true && vexRT[Btn6U] ==0)
	{
		buttonPressed = false;
		additionalSpeed+=20;
	}
	if(buttonPressed == true && vexRT[Btn6D] ==0)
	{
		buttonPressed=false;
		additionalSpeed+=-20;
	}


}
