#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    X_accel,        sensorAccelerometer)
#pragma config(Sensor, in2,    Y_accel,        sensorAccelerometer)
#pragma config(Sensor, in3,    Z_accel,        sensorAccelerometer)
#pragma config(Sensor, in4,    UpLightSensor,  sensorLineFollower)
#pragma config(Sensor, in5,    BtmLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LauncherIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           UpIntake,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float wheel = 0;
int boost = 0;

task Launcher()
{
if(vexRT[Btn6U]== 1)
	{
		boost =-3;
	}
	if((vexRT[Btn6U] == 0) && (vexRT[Btn6D] == 0))
	{
		boost = 0;
	}
	if(vexRT[Btn6D] == 1)
	{
		boost = 3;
	}

	if(vexRT(Btn7R))
	{
		wheel =0;
	}
	if(vexRT[Btn7U] ==1)
	{
		motor[BtmIntake] = 70;
	}
	else
	{
		motor[BtmIntake]=0;
	}
	if(vexRT[Btn7D] ==1)
	{
		motor[BtmIntake] = -70;
	}
	else
	{
		motor[BtmIntake]=0;
	}

	if(vexRT[Btn7L] ==1)
	{
		motor[UpIntake] = -127;
	}
	else
	{
		motor[UpIntake] =0;
	}

	if(vexRT(Btn8L))
	{
		wheel= -40;
	}

	if(vexRT(Btn8D))
	{
		wheel= -50;
	}
	if(vexRT(Btn8R))
	{
		wheel= -55;
	}
	if(vexRT(Btn8U))
	{
		wheel= -60;
	}
		motor[LBtmL]= (wheel+boost);
		motor[LMidL]= (wheel+boost);
		motor[LUpL] = (wheel+boost);
		motor[RBtmL]= (wheel+boost);
		motor[RMidL] = (wheel+boost);
		motor[RUpL] = (wheel+boost);
	}

	task main
	{

	while(true)
	{
		startTask(Launcher);
	}
}
