#pragma config(Motor,  port1,           FrontLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BackLeft,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task driving
{
	while(true)
	{
	motor[FrontLeft]  = vexRT[Ch3];
  motor[FrontRight] = vexRT[Ch2];
  motor[BackLeft]  = vexRT[Ch3];
  motor[BackRight] = vexRT[Ch2];
}
}
	void flybro (int speed)
{
	speed=0;
	motor[BackLeft]= speed;
}

task main()
{
	startTask(driving);
	while(true)
	{
			flybro(60);
if(vexRT[Btn7U] == 1)
{
	{
		flybro (+5);
	}
}


if(vexRT[Btn7R] == 1)
{
	{
		flybro (-5);
	}
}
	wait1Msec(1);
	}

}
