#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LauncherIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          UpIntake,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void controlflywheelmotor (int speed)
{
	motor[LBtmL]= speed;
	motor[LMidL]= speed;
	motor[LUpL] = speed;
	motor[RBtmL]= speed;
	motor[RUpL] = speed;
	motor[RUpL] = speed;
}
task lcdstuff//lcd code
{
	while(true)
	{
	clearLCDLine(0);                      // Clear line 1 (0) of the LCD
  clearLCDLine(1);                      // Clear line 2 (1) of the LCD
  bLCDBacklight = true;                 // Turn on LCD Backlight
  displayLCDPos(0,0);                   // Set the cursor to line 0, position 0 (top line, far left)
  displayNextLCDString("Hello from");   // Display "Hello from"
  displayLCDPos(1,0);                   // Set the cursor to line 1, position 0 (bottom line, far left)
  displayNextLCDString("the other side");
}
}
task driving//driving
{
	while(true)
	{
	motor[LeftDrive] = vexRT(Ch2);
	motor[RightDrive]= vexRT(Ch3);
}
}
task flywheelstuff //manual control for speed
{
	while(true)
	{
	if(vexRT[Btn8L] ==1)
	{
		controlflywheelmotor(70);
		wait1Msec(3000);
	}

	if(vexRT[Btn8D] ==1)
	{
		controlflywheelmotor(75);
		wait1Msec(3000);
	}

	if(vexRT[Btn8R] == 1)
	{
		controlflywheelmotor(80);
		wait1Msec(3000);
	}
	if(vexRT[Btn8U] ==1)
	{
		controlflywheelmotor(90);
		wait1Msec(3000);
	}
}
}
task intake //controls intake
{
	while(true)
	{
		 if(vexRT[Btn6U] == 1)
    {
    	motor[UpIntake] = 127;////
    	motor[BtmIntake] = 127;//

    }
    else if(vexRT[Btn6D] == 1)//
    {
    	motor[UpIntake] = -127;//
    	motor[BtmIntake] = -127;//

    }
   	else
    {
    	motor[UpIntake] = 0;//
    	motor[BtmIntake] = 0;//
    }
  }

}
task main()
{
	startTask(lcdstuff);
	startTask(flywheelstuff);
	startTask(driving);
	startTask(intake);
	while(true)
	{
		wait1Msec(1);
	}

}
