#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    X_accel,        sensorAccelerometer)
#pragma config(Sensor, in2,    Y_accel,        sensorAccelerometer)
#pragma config(Sensor, in3,    Z_accel,        sensorAccelerometer)
#pragma config(Sensor, in4,    UpLightSensor,  sensorLineFollower)
#pragma config(Sensor, in5,    BtmLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LauncherIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          UpIntake,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
int Program;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	 // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	//Leave this value alone
	int lcdScreenMin = 1;
	//This keeps track of which program you want to run
	int lcdScreen = 1;
	//Change this value to be the maximum number of programs you want on the robot
	int lcdScreenMax = 4;
	//Turns on the Backlight
	bLCDBacklight = true;

	//Copied from someone's sample code because the documentation for RobotC won't tell me anything useful
	//These should logically work, but I'm not 100% sure
	const short leftButton = 1;
	const short centerButton = 2;
	const short rightButton = 4;

	while (bIfiRobotDisabled == 1) { //Ensures this code will run ONLY when the robot is disabled
		if (nLCDButtons == leftButton) { //Scrolls to the left
			if (lcdScreenMin == lcdScreen) {
				lcdScreen = lcdScreenMax;
				wait1Msec(250);
			} else {
				lcdScreen --;
				wait1Msec(250);
			}
		}
		if (nLCDButtons == rightButton) { //Scrolls to the right
			if (lcdScreenMax == lcdScreen) {
				lcdScreen = lcdScreenMin;
				wait1Msec(250);
			} else {
				lcdScreen++;
				wait1Msec(250);
			}
		}
		if (lcdScreen == 1 && Program != 1) {
			displayLCDCenteredString (0, "Program"); //Name the first program here
			displayLCDCenteredString (1, "1"); //Name the first program here
			if (nLCDButtons == centerButton) {
				Program = lcdScreen; //Sets the Program to the one on-screen
				displayLCDCenteredString (0, "Autonomous Has");
				displayLCDCenteredString (1, "Been Selected!");
				wait1Msec(1500);
			}
		} else if (lcdScreen == 1 && Program == 1) {
			displayLCDCenteredString (0, "Program"); //We use brackets to mark which program we have chosen
			displayLCDCenteredString (1, "[1]"); //So that while we're scrolling, we can have one marked
		} else if (lcdScreen == 2 && Program != 2) {
			displayLCDCenteredString (0, "Program"); //Name the second program here
			displayLCDCenteredString (1, "2"); //Name the second program here
			if (nLCDButtons == centerButton) {
				Program = lcdScreen; //Sets the Program to the one on-screen
				displayLCDCenteredString (0, "Autonomous Has");
				displayLCDCenteredString (1, "Been Selected!");
				wait1Msec(1500);
			}
		} else if (lcdScreen == 2 && Program == 2) {
			displayLCDCenteredString (0, "Program"); //We use brackets to mark which program we have chosen
			displayLCDCenteredString (1, "[2]"); //So that while we're scrolling, we can have one marked
		} else if (lcdScreen == 3 && Program != 3) {
			displayLCDCenteredString (0, "Program"); //Name the third program here
			displayLCDCenteredString (1, "3"); //Name the third program here
			if (nLCDButtons == centerButton) {
				Program = lcdScreen; //Sets the Program to the one on-screen
				displayLCDCenteredString (0, "Autonomous Has");
				displayLCDCenteredString (1, "Been Selected!");
				wait1Msec(1500);
			}
		} else if (lcdScreen == 3 && Program == 3) {
			displayLCDCenteredString (0, "Program"); //We use brackets to mark which program we have chosen
			displayLCDCenteredString (1, "[3]"); //So that while we're scrolling, we can have one marked
		} else if (lcdScreen == 4 && Program != 4) {
			displayLCDCenteredString (0, "Program"); //Name the fourth program here
			displayLCDCenteredString (1, "4"); //Name the fourth program here
			if (nLCDButtons == centerButton) {
				Program = lcdScreen; //Sets the Program to the one on-screen
				displayLCDCenteredString (0, "Autonomous Has");
				displayLCDCenteredString (1, "Been Selected!");
				wait1Msec(1500);
			}
		} else if (lcdScreen == 4 && Program == 4) {
			displayLCDCenteredString (0, "Program"); //We use brackets to mark which program we have chosen
			displayLCDCenteredString (1, "[4]"); //So that while we're scrolling, we can have one marked
		}
	}

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	if(Program == 1)
	{
		motor[LeftDrive] = -90;
		wait1Msec(3000);
		motor[LeftDrive] = 0;

		//Put your second program in here
	}
	else if(Program == 2)
	{
		motor[RightDrive] = 90;
		wait1Msec(3000);
		motor[RightDrive] = 0;
		//Put your second program in here
	}
	else if(Program == 3)
	{
		motor[RightDrive && LeftDrive] = 90;
		wait1Msec(3000);
		motor[RightDrive && LeftDrive] = 0;
		//Put your third program in here
	}
	else if(Program == 4)
	{
		motor[RightDrive] = 90;
		motor[LeftDrive]  = -90;
		wait1Msec(3000);
		motor[RightDrive] = 0;
		motor[LeftDrive]  = 0;

		//Pur your fourth program in here
	}

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
void controlflywheelmotor (int speed)
{
	motor[LBtmL]= speed;
	motor[LMidL]= speed;
	motor[LUpL] = speed;
	motor[RBtmL]= speed;
	motor[RUpL] = speed;
	motor[RUpL] = speed;
}
task lcdstuff
{
	while(true)
	{
	clearLCDLine(0);                      // Clear line 1 (0) of the LCD
  clearLCDLine(1);                      // Clear line 2 (1) of the LCD
  bLCDBacklight = true;                 // Turn on LCD Backlight
  displayLCDPos(0,0);                   // Set the cursor to line 0, position 0 (top line, far left)
  displayNextLCDString("Hello from");   // Display "Hello from"
  displayLCDPos(1,0);                   // Set the cursor to line 1, position 0 (bottom line, far left)
  displayNextLCDString("the other side");
}
}
task driving
{
	while(true)
	{
	motor[LeftDrive] = vexRT(Ch3);
	motor[RightDrive]= vexRT(Ch2);
	}
}
task flywheelstuff
{
	while(true)
	{
	if(vexRT[Btn8L] ==1)
	{
		controlflywheelmotor(-63);
		wait1Msec(3000);
	}

	if(vexRT[Btn8D] ==1)
	{
		controlflywheelmotor(-65);
		wait1Msec(3000);
	}

	if(vexRT[Btn8R] == 1)
	{
		controlflywheelmotor(-70);
		wait1Msec(3000);
	}
	if(vexRT[Btn8U] ==1)
	{
		controlflywheelmotor(-80);
		wait1Msec(3000);
	}
	else
		{
			wait1Msec(1000);
			controlflywheelmotor(0);
		}
}
}
task intake
{
	while(true)
	{
		 if(vexRT[Btn6U] == 1)
    {
    	motor[UpIntake] = -127;////
    	motor[BtmIntake] = 127;//

    }
    else if(vexRT[Btn6D] == 1)//
    {

    	motor[UpIntake] = 127;//

    }
   	else
    {
    	motor[UpIntake] = 0;//
    	motor[BtmIntake] = 0;//
    }
  }

}
task usercontrol()
{

	startTask(lcdstuff);
	startTask(flywheelstuff);
	startTask(driving);
	startTask(intake);
	while(true)
	{
		if(vexRT(Btn7D) == 1){
			stopTask(flywheelstuff);}
		wait1Msec(1);
	}
}
