#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LaucherIME,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          UpIntake,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while(1 == 1)
  {

    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[RightDrive]  = vexRT[Ch2];
  motor[LeftDrive] = vexRT[Ch3];



    if(vexRT[Btn6U] == 1)
    {
    	motor[UpIntake] = 127;////
    	motor[BtmIntake] = 127;//

    }
    else if(vexRT[Btn6D] == 1)//
    {
    	motor[UpIntake] = -127;//
    	motor[BtmIntake] = -127;//

    }
   	else
    {
    	motor[UpIntake] = 0;//
    	motor[BtmIntake] = 0;//

 	 	}

 	 	if(vexRT[Btn8L] == 1)
 	 	{

 	 		motor[RBtmL] = -75;
    	motor[RMidL] = -75;
    	motor[RUpL] = -75;
    	motor[LBtmL] = -75;
    	motor[LMidL] = -75;
    	motor[LUpL] = -75;

    	wait1Msec(3000);
  	}
		if(vexRT[Btn8D] == 1)
 	 	{
 	 		motor[RBtmL] = -80;
    	motor[RMidL] = -80;
    	motor[RUpL] = -80;
    	motor[LBtmL] = -80;
    	motor[LMidL] = -80;
    	motor[LUpL] = -80;

    	wait1Msec(3000);
  	}
  	if(vexRT[Btn8R] == 1)
 	 	{
 	 		motor[RBtmL] = -85;
    	motor[RMidL] = -85;
    	motor[RUpL] = -85;
    	motor[LBtmL] = -85;
    	motor[LMidL] = -85;
    	motor[LUpL] = -85;

    	wait1Msec(3000);

  	}

  	if(vexRT[Btn8U] == 1)
 	 	{
 	 		motor[RBtmL] = -100;
    	motor[RMidL] = -100;
    	motor[RUpL] = -100;
    	motor[LBtmL] = -100;
    	motor[LMidL] = -100;
    	motor[LUpL] = -100;

    	wait1Msec(3000);
  	}

  	else
  	{
  		motor[RBtmL] = 0;
    	motor[RMidL] = 0;
    	motor[RUpL] = 0;
    	motor[LBtmL] = 0;
    	motor[LMidL] = 0;
    	motor[LUpL] = 0;
    }





  }



}
