#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    X_accel,        sensorAccelerometer)
#pragma config(Sensor, in2,    Y_accel,        sensorAccelerometer)
#pragma config(Sensor, in3,    Z_accel,        sensorAccelerometer)
#pragma config(Sensor, in4,    UpLightSensor,  sensorLineFollower)
#pragma config(Sensor, in5,    BtmLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LauncherIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           BtmIntake,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBtmL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMidL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RMidL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBtmL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RUpL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LUpL,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          UpIntake,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	int speed=0;
	while(1)
{
	if(vexRT[Btn8U] == 20)
	{

	speed+=vexRT[Btn7U];
	speed-=vexRT[Btn7D];
	motor[LBtmL]= speed;
	motor[LMidL]= speed;
	motor[LUpL] = speed;
	motor[RBtmL]= speed;
	motor[RUpL] = speed;
	motor[RUpL] = speed;
wait1Msec(20);
}
}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
