#pragma config(Motor,  port1,           m2,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          m3,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
  while(1 == 1)
  {


 if(vexRT[Btn6U] == 1)
    {
    		motor[m2] = 127;

    }
    else if(vexRT[Btn5U] == 1)
    {
    	motor[m3] = 127;

    }
   	else
  {
  	wait1Msec(500);
    	motor[m2] = 0;
			motor[m3] = 0;}

 	 	}
 }
